modLoader="javafml"
loaderVersion="[31,)"

issueTrackerURL="https://mrcrayfish.com/mods?id=improvedwolves"

[[mods]]
modId="improvedwolves"
version="1.1.0"
displayName="Improved Wolves"
updateJSONURL="https://mrcrayfish.com/mods?id=improvedwolves"
displayURL="https://mrcrayfish.com/mods?id=improvedwolves"
logoFile="examplemod.png"
credits="@Rexxgamesss and @Jor02video on Twitter for ideas"
authors="MrCrayfish"
description='Makes wolves smarter!'

[[dependencies.improvedwolves]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.improvedwolves]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"
